// Code generated by sqlc. DO NOT EDIT.
// source: comment.sql

package db

import (
	"context"
)

const createComment = `-- name: CreateComment :one
INSERT INTO comments (
  blog_id,
  user_id,
  comment
) VALUES (

  $1, $2, $3
) RETURNING id, blog_id, user_id, comment, (SELECT u.name from users as u WHERE u.id = $2) AS name
`

type CreateCommentParams struct {
	BlogID  int32  `json:"blog_id"`
	UserID  int32  `json:"user_id"`
	Comment string `json:"comment"`
}

type CreateCommentRow struct {
	ID      int32       `json:"id"`
	BlogID  int32       `json:"blog_id"`
	UserID  int32       `json:"user_id"`
	Comment string      `json:"comment"`
	Name    interface{} `json:"name"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (CreateCommentRow, error) {
	row := q.db.QueryRowContext(ctx, createComment, arg.BlogID, arg.UserID, arg.Comment)
	var i CreateCommentRow
	err := row.Scan(
		&i.ID,
		&i.BlogID,
		&i.UserID,
		&i.Comment,
		&i.Name,
	)
	return i, err
}

const deleteComment = `-- name: DeleteComment :exec
DELETE FROM comments
WHERE id = $1
`

func (q *Queries) DeleteComment(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteComment, id)
	return err
}

const getComment = `-- name: GetComment :many
SELECT id, blog_id, user_id, comment, (SELECT u.name from users as u WHERE u.id = c.user_id) AS name 
FROM comments as c
WHERE c.blog_id = $1
ORDER BY c.id
`

type GetCommentRow struct {
	ID      int32       `json:"id"`
	BlogID  int32       `json:"blog_id"`
	UserID  int32       `json:"user_id"`
	Comment string      `json:"comment"`
	Name    interface{} `json:"name"`
}

func (q *Queries) GetComment(ctx context.Context, blogID int32) ([]GetCommentRow, error) {
	rows, err := q.db.QueryContext(ctx, getComment, blogID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCommentRow
	for rows.Next() {
		var i GetCommentRow
		if err := rows.Scan(
			&i.ID,
			&i.BlogID,
			&i.UserID,
			&i.Comment,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOneComment = `-- name: GetOneComment :one
SELECT id, blog_id, user_id, comment, (SELECT u.name from users as u WHERE u.id = c.user_id) AS name 
FROM comments as c
WHERE c.id = $1
LIMIT 1
`

type GetOneCommentRow struct {
	ID      int32       `json:"id"`
	BlogID  int32       `json:"blog_id"`
	UserID  int32       `json:"user_id"`
	Comment string      `json:"comment"`
	Name    interface{} `json:"name"`
}

func (q *Queries) GetOneComment(ctx context.Context, id int32) (GetOneCommentRow, error) {
	row := q.db.QueryRowContext(ctx, getOneComment, id)
	var i GetOneCommentRow
	err := row.Scan(
		&i.ID,
		&i.BlogID,
		&i.UserID,
		&i.Comment,
		&i.Name,
	)
	return i, err
}

const updateComment = `-- name: UpdateComment :exec
UPDATE comments AS c
SET comment = $2
WHERE c.id = $1
RETURNING id, blog_id, user_id, comment, (SELECT u.name from users as u WHERE u.id = c.user_id) AS name
`

type UpdateCommentParams struct {
	ID      int32  `json:"id"`
	Comment string `json:"comment"`
}

type UpdateCommentRow struct {
	ID      int32       `json:"id"`
	BlogID  int32       `json:"blog_id"`
	UserID  int32       `json:"user_id"`
	Comment string      `json:"comment"`
	Name    interface{} `json:"name"`
}

func (q *Queries) UpdateComment(ctx context.Context, arg UpdateCommentParams) error {
	_, err := q.db.ExecContext(ctx, updateComment, arg.ID, arg.Comment)
	return err
}
