// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
)

type Blog struct {
	ID       int32          `json:"id"`
	Title    sql.NullString `json:"title"`
	Content  sql.NullString `json:"content"`
	Created  sql.NullTime   `json:"created"`
	Updated  sql.NullTime   `json:"updated"`
	AuthorID sql.NullInt32  `json:"author_id"`
}

type Category struct {
	Title  string        `json:"title"`
	BlogID sql.NullInt32 `json:"blog_id"`
}

type Tag struct {
	Title  string        `json:"title"`
	BlogID sql.NullInt32 `json:"blog_id"`
}

type User struct {
	ID       int32          `json:"id"`
	Username sql.NullString `json:"username"`
	Password sql.NullString `json:"password"`
	Role     sql.NullString `json:"role"`
	Created  sql.NullTime   `json:"created"`
	Updated  sql.NullTime   `json:"updated"`
}

type UserComment struct {
	ID     int32          `json:"id"`
	BlogID sql.NullInt32  `json:"blog_id"`
	UserID sql.NullInt32  `json:"user_id"`
	Coment sql.NullString `json:"coment"`
}
