// Code generated by sqlc. DO NOT EDIT.

package db

import ()

type Blog struct {
	ID       int32  `json:"id"`
	Title    string `json:"title"`
	Content  string `json:"content"`
	AuthorID int32  `json:"author_id"`
}

type Comment struct {
	ID      int32  `json:"id"`
	BlogID  int32  `json:"blog_id"`
	UserID  int32  `json:"user_id"`
	Comment string `json:"comment"`
}

type User struct {
	ID       int32  `json:"id"`
	Username string `json:"username"`
	Password string `json:"password"`
	Name     string `json:"name"`
}
